version: 2.1

jobs:
  build-windows-cli:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Install Windows target
          command: rustup target add x86_64-pc-windows-gnu
      - run:
          name: Install mingw-w64
          command: apt-get update && apt-get install -y mingw-w64
      - run:
          name: Build Windows CLI Release
          command: cargo build --release --target x86_64-pc-windows-gnu
      - store_artifacts:
          path: target/x86_64-pc-windows-gnu/release/OpenE2E.exe
          destination: OpenE2E-CLI_win64.exe

  build-windows-gui:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Install Windows target
          command: rustup target add x86_64-pc-windows-gnu
      - run:
          name: Install mingw-w64
          command: apt-get update && apt-get install -y mingw-w64
      - run:
          name: Build Windows GUI Release
          command: cargo build --release --features gui --target x86_64-pc-windows-gnu
      - store_artifacts:
          path: target/x86_64-pc-windows-gnu/release/OpenE2E.exe
          destination: OpenE2E-GUI_win64.exe

  build-linux-64-cli:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Build Linux 64-bit CLI Release
          command: cargo build --release --target x86_64-unknown-linux-gnu
      - store_artifacts:
          path: target/x86_64-unknown-linux-gnu/release/OpenE2E
          destination: OpenE2E-CLI_linux64.exe

  build-linux-64-gui:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Install dependencies for Slint GUI
          command: apt-get update && apt-get install -y libfontconfig1-dev
      - run:
          name: Build Linux 64-bit GUI Release
          command: cargo build --release --features gui --target x86_64-unknown-linux-gnu
      - store_artifacts:
          path: target/x86_64-unknown-linux-gnu/release/OpenE2E
          destination: OpenE2E-GUI_linux64

workflows:
  build:
    jobs:
      - build-windows-cli
      - build-windows-gui
      - build-linux-64-cli
      - build-linux-64-gui
